# ==============================================================
# Common Test Data — Shared across environments
# ==============================================================

default.payment.amount=1000
default.beneficiary.name=Automation Test
default.payment.type=FED
default.currency=USD
